
token = ''

START = '0'
ENTER_SPEC = '1'
ENTER_FIO = '2'
ENTER_DISTRICT = '3'
ENTER_PASSPORT_FOTO = '4'
ENTER_PERSON_FOTO = '5'
ENTER_AUTO_CATEGORY = '6'
ENTER_AUTO_SUBCATEGORY = '7'
LAST_STEP = '8'
END_REGISTRATION = '9'

WAITING = '0'
ACCEPT = '1'
DECLAIN = '2'
